'use client'

import { useParams } from 'next/navigation'
import { useState, useEffect } from 'react'
import newsData from '../../../content/news.json'
import Link from 'next/link'

interface Article {
  title: string
  link: string
  source: string
  summary: string
  fullSummary?: string
  pubDate?: string
  isPaywalled?: boolean
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 80)
}

function formatDate(dateStr: string) {
  const date = new Date(dateStr)
  return date.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

function getDomain(url: string): string {
  try {
    return new URL(url).hostname.replace('www.', '')
  } catch {
    return 'source'
  }
}

export default function ArticlePage() {
  const params = useParams()
  const slug = params.slug as string
  
  const articles = (newsData as any).articles || []
  const article = articles.find((a: Article) => slugify(a.title) === slug)
  
  if (!article) {
    return (
      <main className="article-page">
        <div className="container">
          <h1>Article Not Found</h1>
          <p>This article may have been removed or the link is incorrect.</p>
          <Link href="/" className="back-link">← Back to Fear Justice</Link>
        </div>
      </main>
    )
  }
  
  return (
    <main className="article-page">
      <div className="container">
        <Link href="/" className="back-link">← Back to Fear Justice</Link>
        
        <header className="article-header">
          <span className="article-source-tag">{article.source}</span>
          {article.isPaywalled && <span className="paywall-tag">$ Paywalled</span>}
          <h1 className="article-page-title">{article.title}</h1>
          {article.pubDate && (
            <p className="article-date">{formatDate(article.pubDate)}</p>
          )}
        </header>
        
        <article className="article-content">
          <div className="article-body">
            {(article.fullSummary || article.summary || '').split('\n\n').map((para: string, i: number) => (
              <p key={i}>{para}</p>
            ))}
          </div>
          
          <div className="article-cta">
            <a 
              href={article.link} 
              target="_blank" 
              rel="noopener noreferrer"
              className="read-original-btn"
            >
              Read original article at {getDomain(article.link)} →
            </a>
          </div>
        </article>
        
        <footer className="article-footer">
          <p>
            This summary was generated by Fear Justice. 
            <Link href="/"> View more news →</Link>
          </p>
        </footer>
      </div>
    </main>
  )
}
